"use client";
import { useState } from "react";
import Link from "next/link";

export default function SubmitPage() {
  const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  async function submit() { if (!file) return; setLoading(true); setMessage("Running six forensic checks..."); const form = new FormData(); form.append("file", file); try { const res = await fetch("/api/verify-document", { method:"POST", body:form }); const data = await res.json(); setMessage(res.ok ? `Audit complete · ${data.verdict || "Report ready"}` : data.error || "Audit could not be completed"); } catch { setMessage("Backend is offline. The upload was not sent."); } finally { setLoading(false); } }
  return <><div className="page-heading"><div><div className="eyebrow">New audit</div><h1>Start with the document.</h1></div><p>Upload a clear source file and let the forensic engine establish the evidence trail.</p></div><div className="split"><section className="soft-panel"><h3>Document payload</h3><p className="muted" style={{fontSize:13}}>Supported by the connected backend: JPEG, PNG and PDF up to 50 MB.</p><div className="form-stack"><label>Verification domain<select defaultValue="finance"><option value="finance">Finance & billing</option><option>Identity & KYC</option><option>HR & employment</option><option>Education</option><option>Legal</option><option>Medical</option></select></label><label>Document type<select defaultValue="invoice"><option value="invoice">Invoice or receipt</option><option>Utility bill</option><option>Identity document</option><option>Resume</option><option>Certificate</option></select></label><label className="dropzone"><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>setFile(e.target.files?.[0] || null)} /><strong>{file ? file.name : "Drop a file here or browse"}</strong><span>{file ? `${(file.size / 1024 / 1024).toFixed(2)} MB ready to inspect` : "PDF, JPG or PNG · 50 MB maximum"}</span></label><button className="button primary" disabled={!file || loading} onClick={submit}>{loading ? "Inspecting..." : "Run forensic audit ↗"}</button>{message && <div className="badge warning">{message}</div>}</div></section><section className="soft-panel"><div className="eyebrow">What happens next</div><h2 style={{marginTop:10}}>Six lenses. One readable result.</h2><div className="detail-list"><div><span>01 / Pixel integrity</span><strong>ELA heatmap</strong></div><div><span>02 / File history</span><strong>Metadata scan</strong></div><div><span>03 / Surface texture</span><strong>Sharpness</strong></div><div><span>04 / Numbers</span><strong>Benford + checksums</strong></div><div><span>05 / Meaning</span><strong>Gemini semantic audit</strong></div></div><Link className="button secondary" href="/review">See review queue</Link></section></div></>;
}
